### ISSUE TITLE
Example code doesn't work in Python 3.10.4

### ISSUE THREAD

**Issue by sventech** [edikedik/eBoruta#3]
Running the simplest example code on the main page results in this error:
```
Boruta trials:   0%|                                                                                                                                                                           | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/sven/code/tmp/eboruta/test.py", line 7, in <module>
    selector.fit(x, y)
  File "/Users/sven/Library/Caches/pypoetry/virtualenvs/test-eboruta-LpE7ZgEB-py3.10/lib/python3.10/site-packages/eBoruta/algorithm.py", line 394, in fit
    assert len(real_imp) == len(
AssertionError: size of real_imp != size of initial columns
```

**Comment by edikedik** [comment]
Hi @sventech 

Thanks for bringing this up. The issue was related to the output of the `shap` tree explainer. Now features should be aggregated correctly. Please pull the current version from GitHub and reach out if you still encounter any issues.
